// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Btn: typeof import('./src/components/common/Btn.vue')['default']
    Card: typeof import('./src/components/common/Card.vue')['default']
    EditSelect: typeof import('./src/components/EditSelect.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Error: typeof import('./src/components/common/Error.vue')['default']
    IconBtn: typeof import('./src/components/common/IconBtn.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    NewIcon: typeof import('./src/components/common/NewIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SearchCard: typeof import('./src/components/SearchCard.vue')['default']
    Voice: typeof import('./src/components/Voice.vue')['default']
    VoiveBtn: typeof import('./src/components/common/VoiveBtn.vue')['default']
    Waterfall: typeof import('./src/components/common/Waterfall.vue')['default']
  }
}

export {}
